# Generated by Django 4.1.3 on 2022-12-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_remove_club_description_remove_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball.club'),
        ),
    ]
